DROP DATABASE IF EXISTS COOLBOOKS_DB;

CREATE DATABASE COOLBOOKS_DB;

USE COOLBOOKS_DB;                        

CREATE USER IF NOT EXISTS 'coolbooks'@'localhost' IDENTIFIED BY 'coolbooks8055';

GRANT ALL PRIVILEGES ON COOLBOOKS_DB.* TO 'coolbooks' @'localhost'
WITH
GRANT OPTION;

flush PRIVILEGES